### PR TITLE
running libreoffice required HOME var to be set

### PR DESCRIPTION
**Pull request by busgurlu**

### CODE REVIEW

**Comment by zxp86021** [comment]
Hi @busgurlu 
thanks for your contribution
can you let us know what's your environment?
because we did not face any problem on original code

**Comment by busgurlu** [comment]
I had the problem on Ubuntu 16.04 running Apache.

**Comment by zxp86021** [comment]
@busgurlu thanks

**Comment by zxp86021** [comment]
@busgurlu we recommand you to check the user's home directory who use to run your webserver
for example, we use nginx as our webserver, and the user to run nginx is `www-data`.
in `/etc/passwd`, home directory for `www-data` is `/var/www`.
if `/var/www` is not writable for `www-data`, you will get error message.

**Pull request merged**
